name: Sync with Hugging Face Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync with Hugging Face
      uses: nateraw/huggingface-sync-action@v0.0.5
      with:
        github_repo_id: karlosmatos/youtube_converter
        huggingface_repo_id: karelmaly/youtubeconverter
        repo_type: space
        space_sdk: streamlit
        hf_token: ${{ secrets.HF_TOKEN }}
